# Generated by Django 2.1.3 on 2018-11-12 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_login', models.DateTimeField()),
                ('time_logout', models.DateTimeField(null=True)),
                ('duration', models.DurationField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=7)),
                ('first_name', models.CharField(max_length=128)),
                ('middle_initial', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('sex', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1)),
                ('cp_contact_number', models.CharField(max_length=11)),
                ('is_login', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='login',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Officer'),
        ),
    ]
