# Generated by Django 2.1.3 on 2018-11-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='id',
        ),
        migrations.AlterField(
            model_name='officer',
            name='student_number',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
