# Generated by Django 2.1.3 on 2018-11-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_auto_20181113_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='temp_stn',
            field=models.CharField(default='0000000', max_length=7),
        ),
    ]
