# Generated by Django 2.1.3 on 2018-11-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_login_temp_stn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='temp_stn',
            field=models.CharField(default='', max_length=7),
        ),
    ]
