# Generated by Django 2.1.3 on 2018-11-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_auto_20181113_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='daily_time_spent',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='latest_login',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='latest_logout',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='weekly_time_spent',
            field=models.DurationField(null=True),
        ),
    ]
