# Generated by Django 2.1.3 on 2018-11-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_auto_20181113_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='date',
        ),
        migrations.AddField(
            model_name='officer',
            name='daily_time_spent_hour',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='daily_time_spent_minutes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='weekly_time_spent_hour',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='weekly_time_spent_minutes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='time_login',
            field=models.DateTimeField(),
        ),
    ]
