# Generated by Django 2.1.3 on 2018-11-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_auto_20181113_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='latest_login',
            field=models.DateTimeField(default=None),
        ),
    ]
