# Generated by Django 2.1.3 on 2018-11-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_auto_20181113_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='daily_time_spent',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='daily_time_spent_hour',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='daily_time_spent_minutes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='latest_login',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='latest_logout',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='weekly_time_spent',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='weekly_time_spent_hour',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='weekly_time_spent_minutes',
            field=models.IntegerField(null=True),
        ),
    ]
