# Generated by Django 2.1.3 on 2018-11-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_auto_20181113_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='cp_contact_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='daily_time_spent',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='daily_time_spent_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='daily_time_spent_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='latest_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='latest_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='weekly_time_spent',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='weekly_time_spent_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='weekly_time_spent_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
