# Generated by Django 2.1.3 on 2018-11-13 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0013_auto_20181113_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='daily_time_spent',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='officer',
            name='weekly_time_spent',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
